### ISSUE TITLE
Unexpected background color on bitmap subtitles rendering

### ISSUE THREAD

**Issue by blindwrite** [kingslay/KSPlayer#269]
Sample (pgssub & dvdsub):
https://github.com/blindwrite/FileHolder/raw/video_samples/bitmap_subtitles_background_sample_1_trimmed.mkv

Illustration:
![d075caa33cb6930843661bfa92a447f](https://user-images.githubusercontent.com/62744692/182514662-66c5db9f-efc6-40a4-bca6-251812115fa4.png)
(this comes from a pgssub stream, but the same for dvdsub)

----

Another sample, as in #267 :
https://github.com/qiudaomao/MPVColorIssue/raw/master/MPVColorIssue/resources/captain.marvel.2019.2160p.uhd.bluray.x265-terminal.sample.mkv

![photo_2022-08-03_11-03-16](https://user-images.githubusercontent.com/62744692/182515203-780cabe9-0955-4f5a-a090-527490d350d5.jpg)

----

With https://github.com/kingslay/KSPlayer/commit/e0d9093a3f2f2648c50e49392bec658a6ef6c990, #267 has been fixed. However, there's an unwanted background color beneath the subtitle and varies across different videos. 

In the firest sample, the background color is white and it's almost opaque, while the second sample has a blue one and not fully opaque.

**Comment by kingslay** [comment]
You can try it with the latest code. i fixed this

**Comment by blindwrite** [comment]
Let me apologize for missing the latests commits. With the latest develop branch, it indeeds is working on macOS. 

However, this issue is still reproduceable in iOS devices. The latest commits do not seem to improve the rendering for iOS.

**Comment by kingslay** [comment]
I saw that there will be no problems with the iOS simulator, but there will be problems with the real machine. I have not found the specific reason.
