### ISSUE TITLE
rtsp not supported

### ISSUE THREAD

**Issue by dk-smart-tech** [kingslay/KSPlayer#79]
//player setup

```
let player = IOSVideoPlayerView()
KSPlayerManager.secondPlayerType = KSMEPlayer.self
let container = UIView()
container.frame = frame
container.addSubview(player)
player.frame = container.bounds
player.set(resource: KSPlayerResource(url: URL(string: "rtsp://192.72.1.1/liveRTSP/v3")!))
player.play()

```

//Error log
```
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSAVPlayer
KSPlayer: KSAVPlayer.swift:394 prepareToPlay() | prepareToPlay KSPlayer.KSAVPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - buffering
 NSURLConnection finished with error - code -1002
 NSURLConnection finished with error - code -1002
 ca_require: IsStreamFormatWritable(inScope, inElement) NotWritable
 Metal GPU Frame Capture Enabled
 Metal API Validation Enabled
KSPlayer: KSAVPlayer.swift:418 shutdown() | shutdown KSPlayer.KSAVPlayer
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSMEPlayer
KSPlayer: KSMEPlayer.swift:245 prepareToPlay() | prepareToPlay KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - error
KSPlayer: KSPlayerLayer.swift:298 finish(player:error:) | Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSLocalizedDescription=avformat can't open input, NSUnderlyingError=0x282928cc0 {Error Domain=FFmpegDomain Code=-1330794744 "Protocol not found" UserInfo={NSLocalizedDescription=Protocol not found}}}
```

@kingslay  Could you point me in the right direction? As per readme rtsp is supported, but I seem to get the error show above.

**Comment by dk-smart-tech** [comment]
@kingslay  Thank you for the quick update. But this commit doesn't fix the issue.  


//Error log
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSAVPlayer
KSPlayer: KSAVPlayer.swift:394 prepareToPlay() | prepareToPlay KSPlayer.KSAVPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - buffering
2020-09-12 20:55:40.930781-0700 Wifi Dash Cam[2877:1364739] NSURLConnection finished with error - code -1002
2020-09-12 20:55:40.981123-0700 Wifi Dash Cam[2877:1364728] NSURLConnection finished with error - code -1002
2020-09-12 20:55:41.056062-0700 Wifi Dash Cam[2877:1364718]  ca_require: IsStreamFormatWritable(inScope, inElement) NotWritable
2020-09-12 20:55:41.062234-0700 Wifi Dash Cam[2877:1364718] Metal GPU Frame Capture Enabled
2020-09-12 20:55:41.063957-0700 Wifi Dash Cam[2877:1364718] Metal API Validation Enabled
KSPlayer: KSAVPlayer.swift:418 shutdown() | shutdown KSPlayer.KSAVPlayer
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSMEPlayer
KSPlayer: KSMEPlayer.swift:245 prepareToPlay() | prepareToPlay KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - error
KSPlayer: KSPlayerLayer.swift:298 finish(player:error:) | Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSLocalizedDescription=avformat can't open input, NSUnderlyingError=0x2805301b0 {Error Domain=FFmpegDomain Code=-1330794744 "Protocol not found" UserInfo={NSLocalizedDescription=Protocol not found}}}

//From podfile.lock
CHECKOUT OPTIONS:
  KSPlayer:
    :commit: e47381285eccfb3d6c48e140b363e2b223713257
    :git: https://github.com/kingslay/KSPlayer.git
  Openssl:
    :commit: e47381285eccfb3d6c48e140b363e2b223713257
    :git: https://github.com/kingslay/KSPlayer.git

I also tried with  rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov  to make sure the issue not my Livestream. This also doesn't work.

**Comment by dk-smart-tech** [comment]
Also tried with your demo project. I get similar error:

KSPlayer: KSPlayerLayer.swift:183 resetPlayer() | resetPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - notSetURL
KSPlayer: KSMEPlayer.swift:261 shutdown() | shutdown KSPlayer.KSMEPlayer
KSPlayer: MEPlayerItem.swift:391 shutdown() | 清空formatCtx
KSPlayer: KSPlayerLayer.swift:183 resetPlayer() | resetPlayer
KSPlayer: KSMEPlayer.swift:261 shutdown() | shutdown KSPlayer.KSMEPlayer
2020-09-13 09:49:01.016540+0530 demo-SwiftUI[7103:152702]  ca_require: IsStreamFormatWritable(inScope, inElement) NotWritable
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSMEPlayer
KSPlayer: KSMEPlayer.swift:245 prepareToPlay() | prepareToPlay KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - buffering
KSPlayer: MEPlayerItem.swift:88 init(url:options:) | Opening 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov' for reading

KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - error
KSPlayer: KSPlayerLayer.swift:298 finish(player:error:) | Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSUnderlyingError=0x600001aa3540 {Error Domain=FFmpegDomain Code=-1330794744 "Protocol not found" UserInfo={NSLocalizedDescription=Protocol not found}}, NSLocalizedDescription=avformat can't open input}

**Comment by kingslay** [comment]
Thanks for the test link. i had fixed at 0bf51e16dc0b39d9d08edee352d93c1940a539f7

**Comment by dk-smart-tech** [comment]
@kingslay  Thanks for the support, I appreciate you taking the time to fix the issue.

I tried your latest update. but the issue still exists. Details below:

//Player setup 1:
StructPlayerView(resource: KSPlayerResource(url: liveStreamUrl, options:KSOptions(), name: "Live Stream"))

//Error log
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSAVPlayer
KSPlayer: KSAVPlayer.swift:394 prepareToPlay() | prepareToPlay KSPlayer.KSAVPlayer
2020-09-13 20:56:11.832347-0700 Wifi Dash Cam[3190:1469793] NSURLConnection finished with error - code -1002
2020-09-13 20:56:11.907454-0700 Wifi Dash Cam[3190:1469793] NSURLConnection finished with error - code -1002
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - error
KSPlayer: KSPlayerLayer.swift:298 finish(player:error:) | Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x2831278a0 {Error Domain=NSOSStatusErrorDomain Code=-1002 "(null)"}}


//Player setup 2:
let player = IOSVideoPlayerView()
let container = UIView()
container.frame = frame
KSPlayerManager.secondPlayerType = KSMEPlayer.self
container.addSubview(player)
player.frame = container.bounds
player.set(resource: KSPlayerResource(url: url))
player.play()


//Error log

KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSAVPlayer
KSPlayer: KSAVPlayer.swift:394 prepareToPlay() | prepareToPlay KSPlayer.KSAVPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - buffering
2020-09-13 21:03:34.937164-0700 Wifi Dash Cam[3211:1471850] NSURLConnection finished with error - code -1002
2020-09-13 21:03:34.965876-0700 Wifi Dash Cam[3211:1471828] NSURLConnection finished with error - code -1002
2020-09-13 21:03:38.590621-0700 Wifi Dash Cam[3211:1471606]  ca_require: IsStreamFormatWritable(inScope, inElement) NotWritable
2020-09-13 21:03:38.608847-0700 Wifi Dash Cam[3211:1471606] Metal GPU Frame Capture Enabled
2020-09-13 21:03:38.611864-0700 Wifi Dash Cam[3211:1471606] Metal API Validation Enabled
KSPlayer: KSAVPlayer.swift:418 shutdown() | shutdown KSPlayer.KSAVPlayer
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSMEPlayer
KSPlayer: KSMEPlayer.swift:245 prepareToPlay() | prepareToPlay KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - error
KSPlayer: KSPlayerLayer.swift:298 finish(player:error:) | Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSLocalizedDescription=avformat can't open input, NSUnderlyingError=0x2831d8cf0 {Error Domain=FFmpegDomain Code=-1330794744 "Protocol not found" UserInfo={NSLocalizedDescription=Protocol not found}}}

**Comment by kingslay** [comment]
the url is rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov?  you can try the demo

```
  if let url = URL(string: "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8") {
            objects.append(KSPlayerResource(url: url, options: KSOptions(), name: "m3u8视频"))
        }
```
Replace it with the rtsp url
```
        if let url = URL(string: "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov") {
            objects.append(KSPlayerResource(url: url, options: KSOptions(), name: "m3u8视频"))
        }
```

**Comment by dk-smart-tech** [comment]
Yes, I tried. The video would never load. Not only the above URL, but I also tried my own live stream as well. same result. 
Just to clarify my live stream works great on the VLC player, so the stream is good.

**Comment by kingslay** [comment]
Are you using an iOS simulator?。

**Comment by dk-smart-tech** [comment]
No. I'm running on an iPad.
iPad 5th Gen iOS 13.6.1

**Podfile:**
pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
pod 'Openssl',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'

**//Code**
let liveStream = URL(string: "rtsp://192.72.1.1/liveRTSP/v3")!
StructPlayerView(resource: KSPlayerResource(definitions:  [KSPlayerResourceDefinition(url: liveStream, definition: "Live Stream")]))


**//Error log**
2020-09-14 05:54:07.134840-0700 Wifi Dash Cam[3451:1562358] [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x156885000; frame = (375 0; 360 667); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x281f714d0>; animations = { bounds.origin=<CABasicAnimation: 0x2811cdf80>; bounds.size=<CABasicAnimation: 0x2811cdfc0>; position=<CABasicAnimation: 0x2811ce020>; }; layer = <CALayer: 0x2811c8c80>; contentOffset: {0, 0}; contentSize: {360, 44}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <KSPlayer.KSSubtitleView: 0x155f6fac0; baseClass = UIControl; frame = (0 0; 375 667); hidden = YES; userInteractionEnabled = NO; layer = <CALayer: 0x2811cd7a0>>>
KSPlayer: KSPlayerLayer.swift:82 player | player is KSPlayer.KSAVPlayer
KSPlayer: KSAVPlayer.swift:394 prepareToPlay() | prepareToPlay KSPlayer.KSAVPlayer
2020-09-14 05:54:07.164264-0700 Wifi Dash Cam[3451:1562552] NSURLConnection finished with error - code -1002
2020-09-14 05:54:07.238242-0700 Wifi Dash Cam[3451:1562593] NSURLConnection finished with error - code -1002
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - error
KSPlayer: KSPlayerLayer.swift:298 finish(player:error:) | Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x281f64ab0 {Error Domain=NSOSStatusErrorDomain Code=-1002 "(null)"}}

**Comment by kingslay** [comment]
you can try a5711557cd125ff59bccc8ef5ec949bcc643ddc9 on demo
![image](https://user-images.githubusercontent.com/3964055/93090360-3b31bd00-f6cf-11ea-9372-203701c731da.png)

**Comment by dk-smart-tech** [comment]
I can confirm the video is playing well in your demo and on my project. The piece I was missing was:
```

if url.absoluteString.hasPrefix("rtsp"){
			 options.formatContextOptions["timeout"] = 0
}
```
